apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-app.fullname" . }}
  labels:
    {{- include "backend-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "backend-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-prod-pass
                key: password
          - name: GO_ENV
            value: production

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
